# Generated by Django 5.2.16 on 2026-07-28 14:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0004_preciopunto_margen'),
        ('puntos', '0002_deposito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('tipo', models.CharField(choices=[('precio_unitario', 'Precio especial por unidad'), ('porcentaje', '% de descuento'), ('precio_grupo', 'Precio por el conjunto (2x$1500, combo)'), ('paga_n', 'Llevá N, pagá M (3x2)')], max_length=16, verbose_name='tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor')),
                ('alcance', models.CharField(choices=[('todos', 'Todos los puntos'), ('seleccionados', 'Solo los puntos elegidos')], default='seleccionados', max_length=14, verbose_name='alcance')),
                ('desde', models.DateField(default=django.utils.timezone.localdate, verbose_name='desde')),
                ('hasta', models.DateField(blank=True, help_text='Vacío: la oferta no vence.', null=True, verbose_name='hasta')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
                ('veces_max_por_venta', models.PositiveSmallIntegerField(blank=True, help_text='Cuántas veces puede aplicarse en una misma venta. Vacío: sin tope.', null=True, verbose_name='tope por venta')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofertas', to=settings.AUTH_USER_MODEL, verbose_name='creada por')),
                ('puntos', models.ManyToManyField(blank=True, related_name='ofertas', to='puntos.punto', verbose_name='puntos')),
            ],
            options={
                'verbose_name': 'oferta',
                'verbose_name_plural': 'ofertas',
                'ordering': ['-desde', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='OfertaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField(default=1, verbose_name='cantidad')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ofertas.oferta', verbose_name='oferta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oferta_items', to='catalogo.producto', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'ítem de oferta',
                'verbose_name_plural': 'ítems de oferta',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('oferta', 'producto'), name='oferta_item_unico'), models.CheckConstraint(condition=models.Q(('cantidad__gte', 1)), name='oferta_item_cantidad_positiva')],
            },
        ),
    ]
