# Generated by Django 5.2.16 on 2026-07-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Punto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='dirección')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
            ],
            options={
                'verbose_name': 'punto',
                'verbose_name_plural': 'puntos',
                'ordering': ['nombre'],
            },
        ),
    ]
