# Generated by Django 5.2.16 on 2026-07-21 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('puntos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Ingreso de mercadería'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('venta', 'Venta'), ('transf_in', 'Transferencia (entrada)'), ('transf_out', 'Transferencia (salida)')], max_length=12, verbose_name='tipo')),
                ('cantidad', models.IntegerField(verbose_name='cantidad (delta)')),
                ('resultante', models.PositiveIntegerField(verbose_name='saldo resultante')),
                ('nota', models.CharField(blank=True, max_length=255, verbose_name='nota')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='catalogo.producto', verbose_name='producto')),
                ('punto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='puntos.punto', verbose_name='punto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'movimiento de stock',
                'verbose_name_plural': 'movimientos de stock',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='StockPunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='cantidad')),
                ('stock_minimo', models.PositiveIntegerField(default=0, verbose_name='stock mínimo')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='catalogo.producto', verbose_name='producto')),
                ('punto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='puntos.punto', verbose_name='punto')),
            ],
            options={
                'verbose_name': 'stock por punto',
                'verbose_name_plural': 'stock por punto',
                'constraints': [models.UniqueConstraint(fields=('producto', 'punto'), name='stock_unico_por_producto_punto')],
            },
        ),
    ]
