# Generated by Django 5.2.16 on 2026-07-21 15:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('puntos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.DateTimeField(auto_now_add=True, verbose_name='inicio')),
                ('hora_fin', models.DateTimeField(blank=True, null=True, verbose_name='fin')),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='monto inicial')),
                ('monto_final', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='monto final (arqueo)')),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=8, verbose_name='estado')),
                ('punto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jornadas', to='puntos.punto', verbose_name='punto')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jornadas', to=settings.AUTH_USER_MODEL, verbose_name='vendedor')),
            ],
            options={
                'verbose_name': 'jornada',
                'verbose_name_plural': 'jornadas',
                'ordering': ['-hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=8, verbose_name='tipo')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto')),
                ('motivo', models.CharField(blank=True, max_length=200, verbose_name='motivo')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja', to='caja.jornada', verbose_name='jornada')),
            ],
            options={
                'verbose_name': 'movimiento de caja',
                'verbose_name_plural': 'movimientos de caja',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddConstraint(
            model_name='jornada',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'abierta')), fields=('vendedor',), name='una_jornada_abierta_por_vendedor'),
        ),
    ]
