# Generated by Django 5.2.16 on 2026-07-21 15:24

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('puntos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160, verbose_name='nombre')),
                ('costo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='costo (referencia)')),
                ('alicuota_iva', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, verbose_name='alícuota IVA (%)')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='catalogo.categoria', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CodigoBarras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='código')),
                ('principal', models.BooleanField(default=False, verbose_name='principal')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos', to='catalogo.producto', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'código de barras',
                'verbose_name_plural': 'códigos de barras',
                'ordering': ['-principal', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='PrecioPunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='precio de venta')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('punto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='puntos.punto', verbose_name='punto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='catalogo.producto', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'precio por punto',
                'verbose_name_plural': 'precios por punto',
                'constraints': [models.UniqueConstraint(fields=('producto', 'punto'), name='precio_unico_por_producto_punto')],
            },
        ),
    ]
