# Generated by Django 5.2.16 on 2026-07-21 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('puntos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('completada', 'Completada')], default='completada', max_length=12, verbose_name='estado')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('punto_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_entrada', to='puntos.punto', verbose_name='destino')),
                ('punto_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_salida', to='puntos.punto', verbose_name='origen')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'transferencia',
                'verbose_name_plural': 'transferencias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='TransferenciaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='cantidad')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencia_items', to='catalogo.producto', verbose_name='producto')),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transferencias.transferencia', verbose_name='transferencia')),
            ],
            options={
                'verbose_name': 'ítem de transferencia',
                'verbose_name_plural': 'ítems de transferencia',
            },
        ),
    ]
