# Generated by Django 5.2.16 on 2026-07-28 15:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='descuento'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='oferta',
            field=models.ForeignKey(blank=True, help_text='La oferta que más descontó en esta línea.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='ofertas.oferta', verbose_name='oferta'),
        ),
        migrations.AddField(
            model_name='venta',
            name='descuento_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='descuento por ofertas'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='precio de lista'),
        ),
    ]
